namespace: recruitment-ns

recruitmentApp:
  name: recruitment-app
  replicas: 2

  image:
    repository: amritarecruitacr.azurecr.io/recruitment-app
    tag: "11336"

  containerPort: 3000

  service:
    name: recruitment-service
    type: LoadBalancer
    port: 80
    targetPort: 3000

  env:
    # ⬇️ Added credentials + authSource
    MONGODB_URI: mongodb://admin:StrongPassword123!@mongodb-service:27017/recruitmentdb?authSource=admin
    NODE_ENV: production


mongodb:
  name: mongodb
  replicas: 1

  image: mongo
  tag: "6.0"
  containerPort: 27017

  service:
    name: mongodb-service
    type: ClusterIP
    port: 27017

  pvc:
    name: mongodb-pvc
    accessMode: ReadWriteOnce
    storageClassName: managed-csi
    size: 20Gi


secret:
  name: mongodb-secret
  username: admin
  password: StrongPassword123!
