apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  MONGO_DB_NAME: {{ .Values.mongodb.database | quote }}

