apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.mongodb.username | quote }}
  MONGO_PASSWORD: {{ .Values.mongodb.password | quote }}
