apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recruitment-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/amritasannigrahi3944-sys/Recruitment-App-Project.git
    targetRevision: azure-devops          # OK if this branch exists
    path: HelmChart                       # ✅ Chart root (correct)
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: recruitment-ns             # ✅ Managed by Argo CD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


