apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: candidate-pvc
  namespace: recruitment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
