apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
  namespace: recruitment
spec:
  type: ClusterIP
  selector:
    app: recruitment-service
  ports:
    - port: 80
      targetPort: 3000
