apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_USERNAME: {{ .Values.secret.username | b64enc }}
  MONGO_PASSWORD: {{ .Values.secret.password | b64enc }}
