apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.RecruitmentPVC.name }}
spec:
  accessModes:
    - {{ .Values.RecruitmentPVC.accessMode }}
  storageClassName: {{ .Values.RecruitmentPVC.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.RecruitmentPVC.size }}
