apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  MONGODB_URI: "{{ .Values.recruitmentApp.env.MONGODB_URI }}"
  PORT: "{{ .Values.recruitmentApp.env.PORT }}"
  HOST: "{{ .Values.recruitmentApp.env.HOST }}"
  NODE_ENV: "{{ .Values.recruitmentApp.env.NODE_ENV }}"


