apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recruitmentApp.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.recruitmentApp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.recruitmentApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.recruitmentApp.name }}
    spec:
      imagePullSecrets:                # 👈 ADD HERE
        - name: acr-secret              # 👈 THIS LINE
      containers:
        - name: {{ .Values.recruitmentApp.name }}
          image: {{ .Values.recruitmentApp.image.repository }}:{{ .Values.recruitmentApp.image.tag }}
          ports:
            - containerPort: {{ .Values.recruitmentApp.containerPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.recruitmentApp.env.NODE_ENV | quote }}
            - name: MONGODB_URI
              value: {{ .Values.recruitmentApp.env.MONGODB_URI | quote }}
